In [55]:
import numpy as np
import scipy.ndimage

%load_ext autoreload
%autoreload 2

path = '/home/nol/atom_pjs/ai_pro/'
import sys
sys.path.insert(0, path)

import life as ca



The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [56]:
an_array = np.random.randint(2, size=(10, 10))
weights = np.array([[1, 1, 1],
                    [1, 10, 1],
                    [1, 1, 1]])

In [57]:
an_array

array([[0, 1, 1, 1, 0, 0, 0, 0, 1, 1],
       [0, 0, 1, 1, 0, 0, 1, 0, 1, 0],
       [1, 0, 1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1, 0, 0, 0, 1, 0],
       [1, 1, 0, 1, 1, 1, 1, 0, 1, 0],
       [1, 1, 1, 0, 1, 0, 1, 0, 0, 0],
       [0, 1, 1, 1, 0, 1, 0, 1, 1, 1],
       [1, 0, 1, 1, 1, 1, 0, 0, 1, 1]])

In [58]:
weights

array([[ 1,  1,  1],
       [ 1, 10,  1],
       [ 1,  1,  1]])

In [59]:
con = scipy.ndimage.filters.convolve(an_array,
                                     weights,
                                     mode='wrap')

In [60]:
con

array([[ 4, 14, 16, 16,  5,  3,  2,  4, 14, 15],
       [ 3,  5, 16, 16,  5,  3, 11,  3, 12,  4],
       [13,  5, 15, 16, 16, 15,  5,  4,  3,  4],
       [14, 15,  5, 16, 16, 16, 14, 13,  3, 14],
       [14,  5, 12,  5, 14,  6, 13,  5, 13,  6],
       [13,  5,  3,  5, 14,  6,  3,  5, 12,  6],
       [14, 15,  4, 14, 14, 15, 12,  4, 11,  5],
       [15, 16, 16,  6, 15,  6, 14,  5,  4,  5],
       [ 6, 16, 16, 16,  6, 14,  4, 13, 14, 15],
       [15,  6, 17, 16, 15, 12,  3,  4, 16, 16]])

In [61]:
live_filter = lambda x : (x == 12) | (x == 13) | (x == 3)

In [62]:
live_filter(3)

True

In [63]:
boolean = (con == 3) | (con == 12) | (con == 13)

In [64]:
an_array = np.int8(boolean)

In [65]:
a_gol = ca.GOL()

In [66]:
a_gol.array

array([[0, 1, 1, 1, 1, 1, 0, 0, 1, 0],
       [1, 1, 0, 1, 1, 1, 0, 0, 0, 1],
       [0, 1, 0, 1, 1, 0, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 0, 1, 0, 0, 1],
       [0, 1, 1, 1, 0, 1, 1, 0, 1, 0],
       [0, 1, 0, 0, 1, 1, 0, 0, 1, 0],
       [1, 1, 0, 0, 0, 0, 1, 0, 1, 1],
       [0, 0, 1, 0, 0, 1, 1, 0, 1, 1],
       [0, 0, 1, 0, 0, 1, 0, 1, 1, 1],
       [0, 0, 1, 1, 0, 1, 1, 1, 1, 1]])

In [79]:
a_gol.step()

In [81]:
a_gol = ca.GOL(n=800)
view = ca.LiveViewer(a_gol)
view.draw()
    

AttributeError: 'NoneType' object has no attribute 'attributes'

In [98]:
-2 % 4

2

In [96]:
1 % -3

-2